apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hpgrahsl-poi-map-app-dev
  annotations:
    argocd/app-name: hpgrahsl-poi-map-app-dev
    backstage.io/kubernetes-id: hpgrahsl-poi-map-app
    backstage.io/kubernetes-namespace: hpgrahsl
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-aro24/hpgrahsl-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.kovj5vhc.eastus.aroapp.io/dev-pipelines/ns/hpgrahsl/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.kovj5vhc.eastus.aroapp.io/k8s/ns/hpgrahsl/deployments/hpgrahsl-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.kovj5vhc.eastus.aroapp.io/#https://github.com/rhdh-aro24/hpgrahsl-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://hpgrahsl-poi-map-app-hpgrahsl.apps.kovj5vhc.eastus.aroapp.io
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/hpgrahsl"
  system: workshop-system-hpgrahsl
  consumesApis:
    - gateway-api-hpgrahsl
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-hpgrahsl
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/hpgrahsl"
